apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fdb-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - fdb-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fdb-scc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fdb-scc
subjects:
- kind: ServiceAccount
  name: fdb-operator
  namespace: FDB_NAMESPACE
