# This serviceaccount will be used to access the Thanos endpoints
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-thanos
---
# Generate a permanent SA token - not done by default OpenShift 4.11+
apiVersion: v1
kind: Secret
metadata:
  name: grafana-thanos-token
  annotations:
    kubernetes.io/service-account.name: grafana-thanos
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-monitoring-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: grafana-thanos
  namespace: GRAFANA_NAMESPACE