apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "fdbexporter.labels" . | nindent 4 }}
  name: {{ include "fdbexporter.fullname" . }}
spec:
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      port: {{ .Values.serviceMonitor.port }}
      scheme: {{ .Values.serviceMonitor.scheme }}
      path: {{ .Values.serviceMonitor.path }}
      bearerTokenSecret:
        key: ''
  namespaceSelector:
    matchNames:
      {{- toYaml .Values.namespaceSelector.matchNames | nindent 8 }}
  selector:
    matchLabels:
      {{- include "fdbexporter.selectorLabels" . | nindent 4 }}
